name: ci tests
discover: CI=true npx react-scripts test --listTests --watchAll=false
run: JEST_JUNIT_OUTPUT_FILE="<< outputs.junit >>" JEST_JUNIT_ADD_FILE_ATTRIBUTE="true" CI=true npx react-scripts test --runInBand << test.atoms >> --reporters=jest-junit
analysis: |
  CIRCLECI_COVERAGE="<< outputs.circleci-coverage >>" CI=true npx jest \
    --config jest.config.analysis.js \
    --runInBand \
    --silent \
    --bail \
    << test.atoms >>
outputs:
  junit: test-reports/results.xml
  circleci-coverage: coverage/circleci-coverage.json
options:
  test-impact-analysis: true
  store-test-results: true
